SQL Version of IAPO Data
  
This file contains the same data used in the DynamoDB design for the IAPO system but formatted as SQL INSERT statements for the relational database version.
The data is structured differently to fit a SQL database model rather than NoSQL DynamoDB.

INSERT INTO DEPARTMENT (DepartmentID, DepartmentName) VALUES (1, 'Seidenberg School of Computer Science and Information Systems');

INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (1, 'Computer Science', 1);
INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (2, 'Data Science', 1);
INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (3, 'Cybersecurity', 1);
INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (4, 'Software Development and Engineering', 1);
INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (5, 'Applied Artificial Intelligence', 1);
INSERT INTO MAJOR (MajorID, MajorName, DepartmentID) VALUES (6, 'Information Systems', 1);

INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Fall2025', 'Fall', 2025, '2025-09-02', '2025-12-19');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Fall2026', 'Fall', 2026, '2026-08-31', '2026-12-19');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Fall2027', 'Fall', 2027, '2027-08-29', '2027-12-17');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Fall2028', 'Fall', 2028, '2028-08-20', '2028-12-10');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Spring2026', 'Spring', 2026, '2026-01-26', '2026-05-15');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Spring2027', 'Spring', 2027, '2027-01-25', '2027-05-15');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Spring2028', 'Spring', 2028, '2028-01-29', '2028-05-20');
INSERT INTO SEMESTER (SemesterID, SemesterTerm, Year, StartDate, EndDate) VALUES ('Spring2029', 'Spring', 2029, '2029-01-27', '2029-05-18');

INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (1, 1, 30, 15, 12, 3, 3);
INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (2, 2, 30, 24, 6, 0, 3);
INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (3, 3, 30, 18, 12, 0, 3);
INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (4, 4, 36, 18, 12, 6, 3);
INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (5, 5, 30, 15, 15, 0, 3);
INSERT INTO DEGREE_REQUIREMENTS (RequirementID, MajorID, TotalCreditsRequired, CoreCreditsRequired, ElectiveCreditsRequired, CapstoneCreditsRequired, MinimumGPA) VALUES (6, 6, 30, 15, 12, 3, 3);

INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100001, 'William', 'Court', 'williamc@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100002, 'Charlotte', 'Miller', 'charlottem@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100003, 'Sarah', 'Harris', 'sarahmh@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100004, 'Ava', 'Davenport', 'avasd@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100005, 'Jennifer', 'Roberts', 'jenniferdr@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100006, 'James', 'Phillips', 'jamesp@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100007, 'Paul', 'Huang', 'paulhu@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100008, 'Lukas', 'Jafari', 'lukasjaf@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100009, 'Cameron', 'Sanders', 'cameronsan@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100010, 'Dakota', 'Ortega', 'dakotaort@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100011, 'Josephine', 'Ramirez', 'josephineram@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100012, 'Emory', 'Cole', 'emorycol@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100013, 'Dean', 'Jung', 'deanju@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100014, 'Messiah', 'Asad', 'messiahasa@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100015, 'Tyler', 'Brown', 'tylerbr@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100016, 'Lea', 'Iman', 'leaima@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100017, 'Ariel', 'Banks', 'arielban@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100018, 'Sevyn', 'Stevenson', 'sevynstev@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100019, 'Joshua', 'Morris', 'joshuamo@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100020, 'Tori', 'Garcia', 'torigar@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100021, 'Brooke', 'Goodwin', 'brookego@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100022, 'Jesse', 'Fletcher', 'jessefle@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100023, 'Wilson', 'Long', 'wilsonlon@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100024, 'Christian', 'Woods', 'christianwo@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100025, 'Elliot', 'Kane', 'elliotk@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100026, 'Colin', 'Lee', 'colinlee@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100027, 'Bradley', 'Kennedy', 'bradleyken@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100028, 'Kamryn', 'Phillips', 'kamrynphi@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100029, 'Jamiyah', 'Parks', 'jamiyahpa@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100030, 'Amir', 'Yusuf', 'amiryus@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100031, 'Jamie', 'Collin', 'jamiecol@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100032, 'Kairo', 'Watson', 'kairowat@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100033, 'Devin', 'Wright', 'devinwri@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100034, 'Raven', 'Stone', 'ravensto@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100035, 'Jeremy', 'Parker', 'jeremypar@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100036, 'Elijah', 'Gibson', 'elijahgib@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100037, 'James', 'Hassan', 'jameshas@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100038, 'Noah', 'Chen', 'noahch@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100039, 'Daniel', 'Williams', 'danielwil@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100040, 'Angel', 'Reid', 'angelrei@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100041, 'Maliyah', 'Caldwell', 'maliyahcald@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100042, 'Natalia', 'Perez', 'nataliape@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100043, 'Jason', 'Beck', 'jasonbe@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100044, 'Zara', 'Ali', 'zaraal@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100045, 'Malik', 'Matthews', 'malikmat@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100046, 'Liam', 'Lee', 'liamle@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100047, 'Robin', 'Ahmad', 'robinahm@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100048, 'Skyler', 'Watts', 'skylerwa@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100049, 'Christopher', 'Brown', 'christopherbr@pace.edu', 'MS Computer Science', 1);
INSERT INTO STUDENT (StudentID, FirstName, LastName, Email, Degree, MajorID) VALUES (100050, 'Emma', 'Wang', 'emmawa@pace.edu', 'MS Computer Science', 1);

INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS672', 'Intro to Deep Learning', 3, '["classification","convolutional neural networks","deep learning","machine learning","model evaluation","neural networks","recurrent neural networks","supervised learning"]', '["AI Engineer","Data Scientist","Machine Learning Engineer","Research Scientist","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS608', 'Algorithms and Computer Theory', 3, '["algorithms","automata theory","complexity theory","computability","data structures","divide and conquer","graph algorithms","hashing","searching","sorting"]', '["Algorithm Engineer","Backend Engineer","Research Engineer","Software Engineer","Systems Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS627', 'Artificial Intelligence', 3, '["algorithms","artificial intelligence","data structures","heuristics","intelligent systems","natural language processing","pattern recognition","search algorithms"]', '["AI Engineer","Data Scientist","Machine Learning Engineer","NLP Engineer","Research Scientist","Robotics Engineer","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS505', 'Introduction to Computer Science with Java', 4, '["GUI programming","Java","Java collections","OOP","algorithms","arrays","classes","conditional statements","data modeling","event-driven programming","interfaces","loop statements","object-oriented programming","polymorphism","primitive data types","queues","searching algorithms","sorting","stacks"]', '["Application Developer","Backend Engineer","Java Developer","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS623', 'Database Management Systems', 3, '["JDBC","SQL","data processing","database design","database management","database security","database systems","entity relationship modeling","normalization","transactions"]', '["Backend Engineer","Data Engineer","Database Administrator","Database Engineer","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS641', 'Mobile Web Content and Development', 3, '["AJAX","CSS","HTML5","mobile applications","mobile web development","quality assurance","user-centered design","web analytics"]', '["Frontend Engineer","Full Stack Engineer","Mobile Developer","Software Engineer","UX Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS612', 'Concepts and Structures in Internet Computing', 3, '["client-server architecture","cloud computing","data communication","distributed systems","internet computing","network protocols","web technologies"]', '["Backend Engineer","Cloud Engineer","Network Engineer","Software Engineer","Systems Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS617', 'Game Programming', 3, '["3D graphics","3D modeling","animation","collision detection","computer graphics","game programming","real-time applications","rendering"]', '["AR/VR Engineer","Game Developer","Graphics Engineer","Simulation Engineer","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS691', 'Computer Science Project 1', 3, '["application development","project management","software design","software development","software engineering","system implementation","technical documentation"]', '["Backend Engineer","Full Stack Engineer","Project Engineer","Software Engineer","Systems Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS661', 'Python Programming', 3, '["NumPy","Pandas","Python programming","data analytics","data cleaning","exploratory data analysis","machine learning","predictive modeling"]', '["AI Engineer","Data Engineer","Data Scientist","Machine Learning Engineer","Software Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS604', 'Computer Systems and Concepts', 3, '["compilers","computer architecture","computer organization","computer systems","low level programming","memory systems","operating systems","processor architecture","programming languages","system design"]', '["Backend Engineer","Cloud Engineer","Operating Systems Engineer","Software Engineer","Systems Engineer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS624', 'Application Development with .NET and Web Services', 3, '[".NET framework","ASP.NET","C# programming","database programming","multithreading","object-oriented programming","web services"]', '[".NET Developer","Backend Engineer","Full Stack Engineer","Software Engineer","Web Application Developer"]', 1);
INSERT INTO COURSE (CourseID, CourseName, Credits, CourseKeywords, CareerTags, MajorID) VALUES ('CS610', 'Introduction to Parallel and Distributed Computing', 3, '["MPI","cloud computing","distributed systems","multicore systems","parallel algorithms","parallel computing"]', '["Backend Engineer","Cloud Engineer","Distributed Systems Engineer","Software Engineer","Systems Engineer"]', 1);

INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS505', 'Bridge');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS604', 'Core');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS608', 'Core');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS610', 'Core');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS612', 'Core');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS623', 'Core');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS627', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS617', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS624', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS641', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS661', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS672', 'Elective');
INSERT INTO MAJOR_COURSE (MajorID, CourseID, RequirementType) VALUES (1, 'CS691', 'Capstone');

INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS623', 'CS604');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS691', 'CS604');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS691', 'CS608');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS691', 'CS623');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS691', 'CS612');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS691', 'CS610');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS627', 'CS608');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS624', 'CS612');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS672', 'CS627');
INSERT INTO PREREQUISITES (CourseID, PrereqCourseID) VALUES ('CS641', 'CS624');

INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5001, 'CS505', 1, 'Fall2025', 'Mr. Webster', 'Online', 'Asynchronous', '00:00', '00:00', 20, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5002, 'CS604', 1, 'Fall2025', 'Dr. Bai', 'Hybrid', 'Monday', '18:00', '20:30', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5003, 'CS604', 2, 'Fall2025', 'Dr. Yung', 'Online', 'Asynchronous', '0:00', '0:00', 30, 22);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5004, 'CS608', 1, 'Fall2025', 'Mr. Evans', 'In Person', 'Wednesday', '12:00', '14:30', 30, 20);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5005, 'CS610', 1, 'Fall2025', 'Dr. Tan', 'Hybrid', 'Tuesday', '20:00', '17:30', 40, 31);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5006, 'CS612', 1, 'Fall2025', 'Dr. Tao', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5007, 'CS612', 2, 'Fall2025', 'Mr. Dale', 'Online', 'Asynchronous', '0:00', '0:00', 30, 28);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5008, 'CS623', 1, 'Fall2025', 'Mr. Ramsay', 'Online', 'Asynchronous', '00:00', '00:00', 30, 27);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5009, 'CS623', 2, 'Fall2025', 'Mrs. Taylor', 'Online', 'Asynchronous', '00:00', '00:00', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5010, 'CS624', 1, 'Fall2025', 'Ms. Cruz', 'In Person', 'Wednesday', '19:30', '17:00', 30, 29);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5011, 'CS641', 1, 'Fall2025', 'Mr. Wang', 'Online', '["Friday","Wednesday"]', '12:00', '14:30', 40, 27);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5012, 'CS661', 1, 'Fall2025', 'Ms. Patel', 'Online', 'Asynchronous', '00:00', '00:00', 30, 21);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5013, 'CS661', 2, 'Fall2025', 'Dr. Davis', 'Online', 'Monday', '19:00', '17:00', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5014, 'CS672', 1, 'Fall2025', 'Dr. Fernandez', 'Hybrid', 'Wednesday', '18:00', '20:30', 30, 16);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5015, 'CS672', 2, 'Fall2025', 'Dr.Collin', 'Online', 'Asynchronous', '0:00', '0:00', 30, 27);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5016, 'CS691', 1, 'Fall2025', 'Mrs. Robinson', 'Online', 'Asynchronous', '00:00', '00:00', 20, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5017, 'CS505', 1, 'Fall2026', 'Mr. Webster', 'Online', 'Asynchronous', '00:00', '00:00', 20, 15);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5018, 'CS505', 2, 'Fall2026', 'Dr.Miller', 'Online', 'Asynchronous', '00:00', '00:00', 20, 8);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5019, 'CS604', 1, 'Fall2026', 'Dr. Bai', 'Hybrid', 'Monday', '18:00', '20:30', 30, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5020, 'CS608', 1, 'Fall2026', 'Dr. Wilson', 'Online', 'Asynchronous', '00:00', '00:00', 30, 26);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5021, 'CS610', 1, 'Fall2026', 'Dr. Tan', 'Hybrid', 'Tuesday', '20:00', '17:30', 40, 38);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5022, 'CS610', 2, 'Fall2026', 'Dr. Asad', 'Online', '" Wednesday"', '19:20', '17:30', 40, 15);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5023, 'CS617', 1, 'Fall2026', 'Dr. Khan', 'Online', 'Asynchronous', '00:00', '00:00', 45, 40);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5024, 'CS623', 1, 'Fall2026', 'Mr. Ramsay', 'Online', 'Asynchronous', '00:00', '00:00', 30, 17);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5025, 'CS624', 1, 'Fall2026', 'Ms. Cruz', 'In Person', 'Wednesday', '19:30', '17:00', 30, 21);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5026, 'CS624', 2, 'Fall2026', 'Mr. Lee', 'Online', 'Asynchronous', '0:00', '0:00', 30, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5027, 'CS627', 1, 'Fall2026', 'Dr. Johnson', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 25);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5028, 'CS627', 2, 'Fall2026', 'Dr. Kim', 'Online', 'Asynchronous', '0:00', '0:00', 30, 25);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5029, 'CS641', 1, 'Fall2026', 'Mr. Wang', 'Online', '["Friday","Wednesday"]', '12:00', '14:30', 40, 21);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5030, 'CS641', 2, 'Fall2026', 'Mr.Yadav', 'Online', 'Asynchronous', '0:00', '0:00', 40, 36);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5031, 'CS661', 1, 'Fall2026', 'Ms. Patel', 'Online', 'Asynchronous', '00:00', '00:00', 30, 28);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5032, 'CS672', 1, 'Fall2026', 'Dr.Collin', 'Online', 'Asynchronous', '0:00', '0:00', 30, 26);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5033, 'CS505', 1, 'Fall2027', 'Mr. Webster', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5034, 'CS505', 2, 'Fall2027', 'Dr.Miller', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5035, 'CS604', 1, 'Fall2027', 'Dr. Bai', 'Hybrid', 'Monday', '18:00', '20:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5036, 'CS604', 2, 'Fall2027', 'Dr. Yung', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5037, 'CS608', 1, 'Fall2027', 'Mr. Evans', 'In Person', 'Wednesday', '12:00', '14:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5038, 'CS608', 2, 'Fall2027', 'Mr. Kon', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5039, 'CS610', 1, 'Fall2027', 'Dr. Tan', 'Hybrid', 'Tuesday', '20:00', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5040, 'CS610', 2, 'Fall2027', 'Dr. Asad', 'Online', '" Wednesday"', '19:20', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5041, 'CS612', 1, 'Fall2027', 'Mr. Dale', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5042, 'CS617', 1, 'Fall2027', 'Dr. Khan', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5043, 'CS623', 1, 'Fall2027', 'Mr. Ramsay', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5044, 'CS623', 2, 'Fall2027', 'Mrs. Taylor', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5045, 'CS624', 1, 'Fall2027', 'Mr. Lee', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5046, 'CS627', 1, 'Fall2027', 'Dr. Johnson', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5047, 'CS661', 1, 'Fall2027', 'Ms. Patel', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5048, 'CS661', 2, 'Fall2027', 'Dr. Davis', 'Online', 'Monday', '19:00', '17:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5049, 'CS691', 1, 'Fall2027', 'Dr. Mart', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5050, 'CS505', 1, 'Fall2028', 'Dr.Miller', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5051, 'CS505', 2, 'Fall2028', 'Ms.Singh', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5052, 'CS604', 1, 'Fall2028', 'Dr. Bai', 'Hybrid', 'Monday', '18:00', '20:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5053, 'CS604', 2, 'Fall2028', 'Mr. Anderson', 'Online', '["Thursday","Tuesday"]', '16:00', '18:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5054, 'CS608', 1, 'Fall2028', 'Dr. Wilson', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5055, 'CS610', 1, 'Fall2028', 'Dr. Tan', 'Hybrid', 'Tuesday', '20:00', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5056, 'CS610', 2, 'Fall2028', 'Dr. Asad', 'Online', '" Wednesday"', '19:20', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5057, 'CS612', 1, 'Fall2028', 'Mr. Dale', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5058, 'CS612', 2, 'Fall2028', 'Dr. Tao', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5059, 'CS617', 1, 'Fall2028', 'Dr. Smith', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5060, 'CS624', 1, 'Fall2028', 'Mr. Lee', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5061, 'CS641', 1, 'Fall2028', 'Mr. Yadav', 'Online', 'Asynchronous', '0:00', '0:00', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5062, 'CS661', 1, 'Fall2028', 'Dr. Davis', 'Online', 'Monday', '19:00', '17:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5063, 'CS672', 1, 'Fall2028', 'Dr. Fernandez', 'Hybrid', 'Wednesday', '18:00', '20:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5064, 'CS672', 2, 'Fall2028', 'Dr.Collin', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5065, 'CS505', 1, 'Spring2026', 'Ms.Singh', 'Online', 'Asynchronous', '00:00', '00:00', 20, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5066, 'CS604', 1, 'Spring2026', 'Mr. Anderson', 'Online', '["Thursday","Tuesday"]', '16:00', '18:30', 30, 25);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5067, 'CS608', 1, 'Spring2026', 'Mr. Kon', 'Online', 'Asynchronous', '00:00', '00:00', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5068, 'CS608', 2, 'Spring2026', 'Mr. Evans', 'In Person', 'Wednesday', '12:00', '14:30', 30, 13);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5069, 'CS610', 1, 'Spring2026', 'Dr. Asad', 'Online', '" Wednesday"', '19:20', '17:30', 40, 26);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5070, 'CS612', 1, 'Spring2026', 'Dr. Tao', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 17);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5071, 'CS612', 2, 'Spring2026', 'Mr. Dale', 'Online', 'Asynchronous', '0:00', '0:00', 30, 10);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5072, 'CS617', 1, 'Spring2026', 'Dr. Khan', 'Online', 'Asynchronous', '00:00', '00:00', 45, 31);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5073, 'CS617', 2, 'Spring2026', 'Dr. Smith', 'Online', 'Asynchronous', '00:00', '00:00', 45, 19);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5074, 'CS623', 1, 'Spring2026', 'Mrs. Taylor', 'Online', 'Asynchronous', '00:00', '00:00', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5075, 'CS624', 1, 'Spring2026', 'Ms. Cruz', 'In Person', 'Wednesday', '19:30', '17:00', 30, 15);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5076, 'CS624', 2, 'Spring2026', 'Mr. Lee', 'Online', 'Asynchronous', '0:00', '0:00', 30, 20);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5077, 'CS627', 1, 'Spring2026', 'Dr. Johnson', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 18);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5078, 'CS691', 1, 'Spring2026', 'Mrs. Robinson', 'Online', 'Asynchronous', '00:00', '00:00', 20, 12);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5079, 'CS505', 1, 'Spring2027', 'Ms.Singh', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5080, 'CS604', 1, 'Spring2027', 'Mr. Anderson', 'Online', '["Thursday","Tuesday"]', '16:00', '18:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5081, 'CS604', 2, 'Spring2027', 'Dr. Yung', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5082, 'CS608', 1, 'Spring2027', 'Dr. Wilson', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5083, 'CS610', 1, 'Spring2027', 'Dr. Asad', 'Online', '" Wednesday"', '19:20', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5084, 'CS612', 1, 'Spring2027', 'Dr. Tao', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5085, 'CS617', 1, 'Spring2027', 'Dr. Khan', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5086, 'CS617', 2, 'Spring2027', 'Dr. Smith', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5087, 'CS641', 1, 'Spring2027', 'Mr. Yadav', 'Online', 'Asynchronous', '0:00', '0:00', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5088, 'CS661', 1, 'Spring2027', 'Dr. Davis', 'Online', 'Monday', '19:00', '17:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5089, 'CS672', 1, 'Spring2027', 'Dr. Fernandez', 'Hybrid', 'Wednesday', '18:00', '20:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5090, 'CS672', 2, 'Spring2027', 'Dr.Collin', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5091, 'CS691', 1, 'Spring2027', 'Dr. Mart', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5092, 'CS691', 2, 'Spring2027', 'Mrs. Robinson', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5093, 'CS505', 1, 'Spring2028', 'Dr.Miller', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5094, 'CS604', 1, 'Spring2028', 'Dr. Yung', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5095, 'CS623', 1, 'Spring2028', 'Mrs. Taylor', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5096, 'CS624', 1, 'Spring2028', 'Ms. Cruz', 'In Person', 'Wednesday', '19:30', '17:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5097, 'CS624', 2, 'Spring2028', 'Mr. Lee', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5098, 'CS627', 1, 'Spring2028', 'Dr. Johnson', 'Online', '["Thursday","Tuesday"]', '15:00', '16:45', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5099, 'CS627', 2, 'Spring2028', 'Dr. Kim', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5100, 'CS641', 2, 'Spring2028', 'Mr. Yadav', 'Online', 'Asynchronous', '0:00', '0:00', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5101, 'CS641', 1, 'Spring2028', 'Mr. Wang', 'Online', '["Friday","Wednesday"]', '12:00', '14:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5102, 'CS672', 1, 'Spring2028', 'Dr. Fernandez', 'Hybrid', 'Wednesday', '18:00', '20:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5103, 'CS691', 1, 'Spring2028', 'Dr. Mart', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5104, 'CS691', 2, 'Spring2028', 'Mrs. Robinson', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5105, 'CS505', 1, 'Spring2029', 'Ms.Singh', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5106, 'CS604', 1, 'Spring2029', 'Mr. Anderson', 'Online', '["Thursday","Tuesday"]', '16:00', '18:30', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5107, 'CS608', 1, 'Spring2029', 'Mr. Khon', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5108, 'CS608', 2, 'Spring2029', 'Dr. Wilson', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5109, 'CS610', 1, 'Spring2029', 'Dr. Tan', 'Hybrid', 'Tuesday', '20:00', '17:30', 40, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5110, 'CS612', 1, 'Spring2029', 'Mr. Dale', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5111, 'CS617', 1, 'Spring2029', 'Dr. Khan', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5112, 'CS617', 2, 'Spring2029', 'Dr. Smith', 'Online', 'Asynchronous', '00:00', '00:00', 45, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5113, 'CS623', 1, 'Spring2029', 'Mr. Ramsay', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5114, 'CS623', 2, 'Spring2029', 'Mrs. Taylor', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5115, 'CS627', 1, 'Spring2029', 'Dr. Kim', 'Online', 'Asynchronous', '0:00', '0:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5116, 'CS661', 1, 'Spring2029', 'Ms. Patel', 'Online', 'Asynchronous', '00:00', '00:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5117, 'CS661', 2, 'Spring2029', 'Dr. Davis', 'Online', 'Monday', '19:00', '17:00', 30, 0);
INSERT INTO Courses_Offered (OfferedID, CourseID, SectionID, SemesterID, Instructor, InstructionalMethod, MeetingDay, StartTime, EndTime, Capacity, CurrentlyEnrolled) VALUES (5118, 'CS691', 1, 'Spring2029', 'Dr. Mart', 'Online', 'Asynchronous', '00:00', '00:00', 20, 0);

INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (1, 100001, 'RequiredDaysOff', 'Friday', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (2, 100005, 'GraduationDeadline', 'Spring 2028', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (3, 100008, 'AvoidTime', '8AM - 5PM', 3);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (4, 100014, 'AvoidDays', 'Thursday', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (5, 100017, 'AvoidInstructionalMethod', 'In Person', 2);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (6, 100021, 'MinCredits', 6, 4);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (7, 100026, 'RequiredDaysOff', 'Wednesday', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (8, 100030, 'GraduationDeadline', 'Spring2027', 2);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (9, 100033, 'PreferredInstructionalMethod', 'Online', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (10, 100039, 'RequiredDaysOff', 'Wednesday, Friday', 1);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (11, 100043, 'PreferredDays', 'Asynchronous', 3);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (12, 100048, 'PreferredTime', 'Evening', 4);
INSERT INTO Student_Constraints (ConstraintID, StudentID, ConstraintType, ConstraintValue, Priority) VALUES (13, 100050, 'MaxCredits', 9, 1);

INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9001, 100001, 5001, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9002, 100001, 5002, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9003, 100001, 5004, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9004, 100001, 5069, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9005, 100001, 5071, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9006, 100001, 5074, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9032, 100005, 5001, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9033, 100005, 5003, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9034, 100005, 5067, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9035, 100005, 5069, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9036, 100005, 5071, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9037, 100005, 5024, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9038, 100005, 5028, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9039, 100005, 5030, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9040, 100005, 5084, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9041, 100005, 5088, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9042, 100005, 5103, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9007, 100008, 5003, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9008, 100008, 5007, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9009, 100008, 5067, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9010, 100008, 5069, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9011, 100014, 5001, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9012, 100014, 5003, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9013, 100014, 5067, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9014, 100014, 5069, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9015, 100014, 5071, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9016, 100014, 5023, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9017, 100014, 5024, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9018, 100014, 5026, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9019, 100014, 5086, 'Optimized');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9020, 100017, 5003, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9021, 100017, 5006, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9022, 100017, 5067, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9023, 100017, 5069, 'Completed');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9024, 100021, 5019, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9025, 100021, 5020, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9026, 100021, 5083, 'Optimized');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9027, 100021, 5084, 'Optimized');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9028, 100021, 5042, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9029, 100021, 5044, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9043, 100021, 5098, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9044, 100021, 5100, 'Draft');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9030, 100026, 5018, 'Accepted');
INSERT INTO Student_Schedule (ScheduleID, StudentID, OfferedID, Status) VALUES (9031, 100026, 5020, 'Accepted');
